### ISSUE TITLE
[Feature proposal] Wrapper (section?) UIElement

### ISSUE THREAD

**Issue by armellarcier** [monsieurbiz/SyliusRichEditorPlugin#108]
A UIElement that wraps around other UIElements, with an id and class names for example.

Would be super useful for custom layouts.

**Comment by jacquesbh** [comment]
I think that it has nothing to do with the Rich Editor, but more with the
Cms Page plugin.

No?

-- 
Monsieur Biz <https://monsieurbiz.com>
@jacquesbh <https://twitter.com/jacquesbh>
+33 (0)6 75 54 11 97
GPG : https://keybase.io/jacquesbh

🦄


Le jeu. 19 nov. 2020 à 12:35, Armel Larcier <notifications@github.com> a
écrit :

**Comment by armellarcier** [comment]
No it's really a matter of adding like 2-3 "wrapper" UIElements inside the same editor, adding an id and/or classes to each one, and having these wrappers behave like a full embedded RichEditor.

**Comment by armellarcier** [comment]
For instance, I need to UIElements, one text and one image, to be on the same row (two cols). I'm building a custom UIElement for that. But it hit me, I could just create a "wrapper" element that could contain any kind of UIElements and do whatever I want in the shop templates, based on any condition on the metadata of the wrapper.

**Comment by jacquesbh** [comment]
Isn't it just a collection?

Have a look at the Ui Element "Image Collection".

But you can't have a Rich Editor in a Ui Element right now. The JS doesn't
work with this kind of loop yet.

-- 
Monsieur Biz <https://monsieurbiz.com>
@jacquesbh <https://twitter.com/jacquesbh>
+33 (0)6 75 54 11 97
GPG : https://keybase.io/jacquesbh

🦄


Le jeu. 19 nov. 2020 à 12:55, Armel Larcier <notifications@github.com> a
écrit :

**Comment by armellarcier** [comment]
A polymorphic collection is doable?

**Comment by armellarcier** [comment]
I'll stick with custom UIElements for now cause they're easy. But I still think the feature would be very nice so users can build pages with flexibility.

**Comment by maximehuran** [comment]
You can create a form type with the wanted form for example : 
- An image
- A text

Then create a CollectionType of this form.
You will create your UI Element with this CollectionFormType.

You will be able to customize the render in front via the template. 

The plugin is provided with very simple elements, but it's very easy to create more complex elements with the config, a form type and a template.
