### ISSUE TITLE
Remove HTML br tag from WYSIWYG text element

### ISSUE THREAD

**Issue by Loocos** [monsieurbiz/SyliusRichEditorPlugin#137]
Hello guys,

I'm wondering how can we remove any tag (for example, the `<br>` tag) from the WYSIWYG text element ?
I didn't found an easy way to do this. 

Why I'm asking that ?
- I'm getting after saving some `<p><br></p>` sometimes
- And a `<br>` at the beginning and end of each content

My version of RichEditor is v2 RC 14

Thanks in advance

**Comment by maximehuran** [comment]
Hi @Loocos how is the behaviour now with the new SunEditor ? https://github.com/monsieurbiz/SyliusRichEditorPlugin/pull/219
