### ISSUE TITLE
TextElement - textarea not clickable in Safari

### ISSUE THREAD

**Issue by Creeperface01** [monsieurbiz/SyliusRichEditorPlugin#149]
I'm unable to edit the content (never get focused) of TextElement in Safari

Safari version: 14.1.1

**Comment by jacquesbh** [comment]
After a small digging, this bug seems to appear only when the Wysiwyg is enabled.

**Comment by comsamarche** [comment]
Hello, 
is anyone resolved this issue ?
I have the same one on the v2.0.11 (Safari 15.6.1)

**Comment by jacquesbh** [comment]
Hi!

We didn't take the needed time to fix this since we are planning to get rid
of the actual wysiwyg for a better tool.

Jacques Bodin-Hullin

-- 
Monsieur Biz
@jacquesbh
+33 (0)6 75 54 11 97
GPG : https://keybase.io/jacquesbh

🦄

**Comment by maximehuran** [comment]
We changed the editor to SunEditor now : 

![image](https://github.com/monsieurbiz/SyliusRichEditorPlugin/assets/11380627/83aabd00-52ac-404f-a671-b4837b07cd48)
