### ISSUE TITLE
[FEATURE] Nested UI elements

### ISSUE THREAD

**Issue by Neirda24** [monsieurbiz/SyliusRichEditorPlugin#172]
We had this use case where we'd like to reuse some UI elements but wrap them in some container.
I tried to do a simple RicheditorType on a UIelement field but doesn't seems to work.

What do you think ?

**Comment by jacquesbh** [comment]
Hey!

We have that in our todo list. Nervertheless it won't be implemented in the RichEditor plugin but in another dedicated one for CMS blocks.

Also we have in the roadmap to implement the capability of copying/pasting some UI elements using the local storage. And this feature will be available in this plugin.

Could it be a solution for you?
