### ISSUE TITLE
How to put it in my product description? Example link is in 404

### ISSUE THREAD

**Issue by tuanth66** [monsieurbiz/SyliusRichEditorPlugin#200]
Hi,
Sorry I'm new with Sylius/php.
I did install your plugin but I don't know how to put it in my product description.
Please classify.

```
Use the Rich Editor
Update your form type

To make a field use the rich editor, you must use the RichEditorType type for it.
We have an example of implementation in the [test application](https://github.com/monsieurbiz/SyliusRichEditorPlugin/blob/master/tests/Application/src/Form/Extension/ProductTypeExtension.php).
```

**Comment by delyriand** [comment]
Hello,

We have a link problem in the README. We'll fix it as soon as possible!

You can look in the dist folder, and more precisely in the [ProductTypeExtension.php ](https://github.com/monsieurbiz/SyliusRichEditorPlugin/blob/master/dist/src/Form/Extension/ProductTypeExtension.php) file.

**Comment by tuanth66** [comment]
> Hello,
> 
> We have a link problem in the README. We'll fix it as soon as possible!
> 
> You can look in the dist folder, and more precisely in the [ProductTypeExtension.php ](https://github.com/monsieurbiz/SyliusRichEditorPlugin/blob/master/dist/src/Form/Extension/ProductTypeExtension.php) file.

Dear delyriand
Thank you very very much.
I create a src/Form/Extension/ProductTypeExtension.php file in my www then the RichEditor show, I click on Add an element and the "Select an UI element" show. I clicked on HTML or other Element but I was do nothing.
Am I missing something, please help!
![ảnh](https://github.com/monsieurbiz/SyliusRichEditorPlugin/assets/99111848/058a4d32-dcbb-4a70-bd25-eb91e5c5987b)

**Comment by delyriand** [comment]
You probably have a JS error (visible in the console tab of your browser's develop toolbar). 

Please check that the assets are correctly installed, and refer to the Sylius doc if necessary.

**Comment by tuanth66** [comment]
Hi, thank you.
It was https in my computer, I'll check it.
Thank you very much!

```
This request has been blocked; the content must be served over HTTPS.
value @ rich-editor-js.js:5
(anonymous) @ rich-editor-js.js:5
```
