### ISSUE TITLE
Sylius 1.13 compatibility

### ISSUE THREAD

**Issue by shochdoerfer** [monsieurbiz/SyliusRichEditorPlugin#228]
I just tried to install the latest version of this plugin in a Sylius 1.13 environment and realized that Composer does not allow this. Are there any bigger blockers to making the plugin compatible with 1.13?

**Comment by jacquesbh** [comment]
Hi @shochdoerfer!

I don't think that we have a big blocker here, just that the PHP version is evolving as well and we need to release accordingly.

So, we need some time to update the plugin.

Would you be willing to make a PR about this? It would be awesome!

Thanks!

**Comment by shochdoerfer** [comment]
@jacquesbh thought about it already ;) Need to figure out when. I was just curious if there are bigger blockers from your POV that require a lot of internal knowledge of how the plugin works. I'll see what I can accomplish...
