### ISSUE TITLE
Add custom tags

### ISSUE THREAD

**Issue by petitbx** [monsieurbiz/SyliusRichEditorPlugin#232]
Hello, 
I'm using your plugin for one of my project on Sylius but I can't understand something. 

I try to add custom CSS or JS on a HTML lame but that's doesn't work, the plugin don't authorize me to add custom CSS or JS in lame. 

I'm on Sylius 1.11.15 with SF 5.4.41 and rich editor 2.7.1

If someone have idea ? 

Thanks a lot

**Comment by jacquesbh** [comment]
Hi,

You should be able to override the templates in your `templates/` directory, or in your Sylius theme.

This way adding CSS and JS should be possible using the Symfony framework tooling!

J
