### ISSUE TITLE
Add ability to set target on buttons

### ISSUE THREAD

**Issue by gabiudrescu** [monsieurbiz/SyliusRichEditorPlugin#237]
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/6520f96e-c9ad-4f3b-8d7e-36ffc45ac1b4">
If I use this type, I am not able to set the link to be opened in another tab/window. 

I believe this would be an easy fix, are you open for a community contribution on this?

**Comment by maximehuran** [comment]
It could be great to have a contribution for that of course :D 

If you change the template for the target _blank.
Don't forget to add `rel="noopener noreferrer"`.

See : https://stackoverflow.com/a/50709724

**Comment by gabiudrescu** [comment]
@maximehuran I felt lucky and submitted a PR. let me know what you think.
