### ISSUE TITLE
This plugin is breaking the javascript in admin

### ISSUE THREAD

**Issue by gabiudrescu** [monsieurbiz/SyliusRichEditorPlugin#24]
see the videos attached. 

this happens after I activate this plugin. 
![Screen Recording 2020-04-02 at 09 41 59](https://user-images.githubusercontent.com/5156054/78218953-51ecaa80-74c7-11ea-883d-e623134f7e35.gif)
![Screen Recording 2020-04-02 at 09 42 53](https://user-images.githubusercontent.com/5156054/78218956-53b66e00-74c7-11ea-8c67-02ad379e222b.gif)

**Comment by jacquesbh** [comment]
Hi @gabiudrescu,

Thank you for reaching us.

Do you have any error in the Javascript console?

Thank you.

**Comment by jacquesbh** [comment]
@gabiudrescu Which version of Sylius are you using?

**Comment by gabiudrescu** [comment]
@jacquesbh I am using Sylius 1.7 with webpack (configured as it is currently recommended in the Sylius docs - which, btw, are not 100% correct) and I see no error in my javascript console. that made this bug really hard to investigate, as I didn't know where to start. 

how I managed to fix this was reverting my last commits, one by one, until this was no longer reproducible. once I discovered this was no longer happening, I went back to master and I have disabled only this plugin and then things started working again. 

to be honest, I had the same problem with Monofony, but the issue there was that some javascripts were missing (and there I had clear console errors in the console of the browser).

**Comment by jacquesbh** [comment]
@gabiudrescu Maybe we could find some time to dig into this issue together during the following weeks?

**Comment by gabiudrescu** [comment]
@jacquesbh sure, we can schedule a call and maybe we can reproduce it and solve it. Let's get in touch on Sylius Slack next week

**Comment by jacquesbh** [comment]
@gabiudrescu Do you still reproduce this bug?

**Comment by gabiudrescu** [comment]
I haven't been able to reproduce it anymore, as we went further without using this plugin. 

I guess you can go with the approach that if no one is complaining, then it's not an actual bug.

**Comment by jacquesbh** [comment]
Thank you @gabiudrescu! The 2.0 release will fix all that in case it's from us, anyway.
