### ISSUE TITLE
Feature proposals

### ISSUE THREAD

**Issue by genosajd** [monsieurbiz/SyliusRichEditorPlugin#248]
Hello, I'm using your plugin and I'm impressed, it is currently the best solution for Sylius and even within the Symfony environment, but it still lacks a lot. It would be great if it could develop like Elementor or DIVI (WordPress).

While working with this editor, I missed a few things, I will list the most important ones:

When I add a block, the list is very large, it would be useful to sort them somehow, for example, by categories, make a sidebar on the left and select categories

The view of all blocks, for example when editing a product, is so long that you have to scroll a lot, I think the ability to collapse or open it as a popup would be a nice solution

Exporting the entire template or block to a JSON file and importing it elsewhere (such an alternative to copying and pasting) or saving them in a database and the ability to quickly create a template for, for example, a product by selecting from the database

Drag & drop? :)

**Comment by jacquesbh** [comment]
Hi!

All those ideas are great!

Sorting by drag and drop can be implemented with a simple PR, we don't need this for now so we won't work on it unless somebody else does.

Grouping UI Elements by category is on our features list, we just need some time to rethink the UI and add the missing parts to avoid BC breaks.

Templates… Yes, that would be a nice feature! It isn't that hard to implement I think, we'll add it to our features list.

Collapsing UI Elements in the admin is a great idea. It comes with UX issues I think. So it has to be done carefully. I'll add it to our features list.

As you can imagine, this features list is implemented on our own timeline :). 

Thank you for those suggestions!
