### ISSUE TITLE
CollectionForm is not a function when adding image collection

### ISSUE THREAD

**Issue by JordiDekker** [monsieurbiz/SyliusRichEditorPlugin#251]
Hi!
I really like to use the RichEditior in various ways to help shop admins to add more data to their pages. When trying to add an image collection the editor is not working as intended:

```
Uncaught TypeError: $(...).find(...).CollectionForm is not a function
```

The default Sylius, where the CollectionForm is defined, is loaded into the page using:
```
<!-- BEGIN BLOCK | event name: "sylius.admin.layout.javascripts", block name: "scripts", template: "@SyliusAdmin/_scripts.html.twig", priority: 10 -->
<script src="/build/admin/admin-entry.js"></script>
<script src="/build/app/admin/app-admin-entry.js"></script>
<!-- END BLOCK | event name: "sylius.admin.layout.javascripts", block name: "scripts" -->
```

I am not sure why the CollectionForm is the only thing that's not working. All other thing of the editor are working fine.

**Comment by maximehuran** [comment]
Hi @JordiDekker !

Which version of Sylius are you using ?

**Comment by JordiDekker** [comment]
@maximehuran Sylius 1.12.19 with RichEditor plugin version 2.10.2.

**Comment by maximehuran** [comment]
Can you provide the full stack of your javascript error ?

**Comment by JordiDekker** [comment]
@maximehuran Hope this helps:

<img width="897" alt="Scherm­afbeelding 2024-12-03 om 15 06 52" src="https://github.com/user-attachments/assets/da269874-9a27-4ff8-950a-219f7302a0c9">


```
new:1122 Uncaught TypeError: $(...).find(...).CollectionForm is not a function
    at HTMLDocument.<anonymous> (new:1122:59)
    at e.value (rich-editor.js:2:789866)
    at e.value (rich-editor.js:2:783175)
    at e.value (rich-editor.js:2:784203)
    at XMLHttpRequest.<anonymous> (rich-editor.js:2:782312)
```

**Comment by maximehuran** [comment]
## Test to reproduce

I set the plugin to the same version of Sylius as you `1.12.19` and plugin to `2.10.2`

![image](https://github.com/user-attachments/assets/d88317ef-2792-4c6e-b77d-75f0a02a1784)

```html
<!-- BEGIN EVENT | event name: "sylius.admin.layout.javascripts" -->
<!-- BEGIN BLOCK | event name: "sylius.admin.layout.javascripts", block name: "scripts", template: "@SyliusAdmin/_scripts.html.twig", priority: 10 -->
<script src="[/build/admin/admin-entry.js](view-source:https://127.0.0.1:8002/build/admin/admin-entry.js)"></script>
<script src="[/build/app/admin/app-admin-entry.js](view-source:https://127.0.0.1:8002/build/app/admin/app-admin-entry.js)"></script>

<!-- END BLOCK | event name: "sylius.admin.layout.javascripts", block name: "scripts" -->
<!-- BEGIN BLOCK | event name: "sylius.admin.layout.javascripts", block name: "legacy", template: "@SyliusUi/Block/_legacySonataEvent.html.twig", priority: 0 -->


<!-- END BLOCK | event name: "sylius.admin.layout.javascripts", block name: "legacy" -->
<!-- BEGIN BLOCK | event name: "sylius.admin.layout.javascripts", block name: "monsieurbiz_richeditor_init_app", template: "@MonsieurBizSyliusRichEditorPlugin/Admin/app.html.twig", priority: 0 -->
<script src="[/bundles/monsieurbizsyliusricheditorplugin/js/rich-editor.js](view-source:https://127.0.0.1:8002/bundles/monsieurbizsyliusricheditorplugin/js/rich-editor.js)"></script>
<link rel="stylesheet" href="[/bundles/monsieurbizsyliusricheditorplugin/css/rich-editor.css](view-source:https://127.0.0.1:8002/bundles/monsieurbizsyliusricheditorplugin/css/rich-editor.css)">

<div class="ui small basic modal" id="monsieurbiz-rich-editor-confirmation-modal">
    <div class="ui icon header">
        <i class="warning sign icon"></i>
        Confirm your action
```

The rich editor app is loaded after the admin javascript and CollectionForm is called correctly

## Possible solutions

You need to have these JS loaded :

`vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-form-collection.js`
`vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-auto-complete.js`

These files are loaded by Sylius in : `vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js`

You webpack config might loaded this JS with this part : 

```js
// Admin config
Encore
  .setOutputPath('public/build/admin/')
  .setPublicPath('/build/admin')
  .addEntry('admin-entry', './vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Resources/private/entry.js')
  .disableSingleRuntimeChunk()
  .cleanupOutputBeforeBuild()
  .enableSourceMaps(!Encore.isProduction())
  .enableVersioning(Encore.isProduction())
  .enableSassLoader();
```

And the `entry.js` in `vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Resources/private/entry.js` will import app with `import './js/app';`

Are you sure you do not have a 404 in your Sylius admin assets ? 

If you comment the line `$(form).find('[data-form-type="collection"]').CollectionForm();`, have you got the error with the next line `$(form).find('.sylius-autocomplete').autoComplete();` ?

**Comment by JordiDekker** [comment]
Hi @maximehuran ,

Thanks a lot for your help. With your examples I found a misconfiguration on our side. Works fine now.

Keep up the good work with this plugin!

**Comment by maximehuran** [comment]
Happy to see your issue resolved !
