### ISSUE TITLE
Error 414 when editing a text lame

### ISSUE THREAD

**Issue by nayluge** [monsieurbiz/SyliusRichEditorPlugin#26]
Hello,

I get a 414 error from nginx when i try to edit a large text lame.

I guess the full content of the lame in a GET parameter is problem.
https://github.com/monsieurbiz/SyliusRichEditorPlugin/blob/93b31cfeac5c05e8b75415212f8c57c92e7c0d59/assets/js/app.js#L324

**Comment by nayluge** [comment]
#27 :)

**Comment by jacquesbh** [comment]
Fixed by #27. Thank you again @nayluge .
