### ISSUE TITLE
Some questions :)

### ISSUE THREAD

**Issue by moafred** [monsieurbiz/SyliusRichEditorPlugin#87]
Hi there ! Thanks for all this works :)

I have some questions:
- It's seems that this plugin provide features like https://github.com/BitBagCommerce/SyliusCmsPlugin, it's cool to have another plugin to have a different implementation, is it in the plan to provide dynamic routes for the frontend to expose the pages builts with this rich editor ? Or a controller that we can call from template like `{{ render(path('monsieur_fait_du_bizbiz_render_page', {'code' : 'homepage''})) }}
`
- Do you have an idea when the 2.0 will be out ? :)

**Comment by jacquesbh** [comment]
Hi!

This plugin provides a Rich Editor, not a full CMS implementation.

You can go here for CMS pages: https://github.com/monsieurbiz/SyliusCmsPagePlugin
And here for your Homepage: https://github.com/monsieurbiz/SyliusHomepagePlugin

The 2.0 is in RC right now, we will test it live in some shops and it will probably be stable by the end of the week! We will update the other CMS plugins with this new version as well :).

Have fun!

**Comment by moafred** [comment]
Thanks @jacquesbh !
