### ISSUE TITLE
Products & taxon products UI elements are missing in v2

### ISSUE THREAD

**Issue by DieterHolvoet** [monsieurbiz/SyliusRichEditorPlugin#98]
I noticed that the products & taxon products UI elements are missing from v2 of the plugin. Are there any plans to bring them back? If not, this should probably be documented in the upgrade guide.

**Comment by jacquesbh** [comment]
Hi!

Yes you are right, we removed a few Ui Elements.
We are planning to provide another plugin which adds more elements. We want this one to be as simple as possible.

Good catch for the upgrade!

**Comment by DieterHolvoet** [comment]
Sounds good, is there a dev version of that new plugin? Or should I implement the products & taxon products elements myself if I need them now?

**Comment by jacquesbh** [comment]
@DieterHolvoet You should implement them by yourself for now.

I suggest using your own `ui_element` class with a proper autowiring. It'll allow you to make a proper render using the `uiElement` variable in your templates.
Like here:
- https://github.com/monsieurbiz/SyliusRichEditorPlugin/blob/ad82315cd71e49a93f028ce30f6b951ca0c2eafa/tests/Application/config/packages/monsieurbiz_sylius_rich_editor_plugin_custom.yaml#L9
- https://github.com/monsieurbiz/SyliusRichEditorPlugin/blob/ad82315cd71e49a93f028ce30f6b951ca0c2eafa/tests/Application/src/UiElement/GoogleMapsUiElement.php#L20-L46
