### ISSUE TITLE
Content of UI element edit dialog overflows

### ISSUE THREAD

**Issue by DieterHolvoet** [monsieurbiz/SyliusRichEditorPlugin#99]
When editing a UI element and the content of the dialog becomes bigger than its container, it overflows and there's no way to scroll.

## Steps to reproduce
1. Add an empty Image Collection element to a rich editor field
2. Edit the newly added element and a couple of new images

**Comment by maximehuran** [comment]
I have the same behaviour. It works when we add an element but not when we are editing it.
